vich_uploader:
    db_driver: orm

    mappings :
        accommodation_image :
            uri_prefix : /images/accommodations 
            upload_destination : '%kernel.project_dir%/public/images/accommodations'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

        attraction_image :
            uri_prefix : /images/attractions 
            upload_destination : '%kernel.project_dir%/public/images/attractions'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
